### ISSUE TITLE
can't close buffers with when the tide-tsserver-executable is not present

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#127]
My `tide-tsserver-executable` is set to always use the project local typescript:

```elisp
(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver"	
      tide-tsserver-directory  "node_modules/typescript/lib")
```

If I open a `.ts` file in a folder with no tsserver, for example by opening `/tmp/a.ts`, I get an `Error from syntax checker typescript-tide: UNKNOWN!` message in the minibuffer, and then is impossible to close the file by using `C-x k`, because it triggers an `Server does not exist. Run M-x tide-restart-server to start it again` error and the buffer is never closed.

**Comment by josteink** [comment]
I've had similar errors in the past, but with no clear cause of the error. 

Using your description, I'll try to reproduce and see if we can't get this fixed once and for all!

**Comment by josteink** [comment]
I've couldn't really reproduce, but I've pushed the following commit to master: https://github.com/ananthakumaran/tide/commit/211059976e7ee70b09cc10396b6285483a963db2

Please let me know if this helps :)

**Comment by nahuel** [comment]
I still get the `Error from syntax checker typescript-tide: UNKNOWN!` message in the minibuffer (correctly, because `tsserver` can't be found) but now I can kill the buffer without getting stuck. Problem solved, thanks!

**Comment by josteink** [comment]
Great! Thanks for reporting back :)
